// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8CztuRmVjIRueRWBUDWRTPOiBGMui5Uw',
    appId: '1:136527670071:web:c3f0596d37076e2fcb08b2',
    messagingSenderId: '136527670071',
    projectId: 'lecture-46',
    authDomain: 'lecture-46.firebaseapp.com',
    databaseURL: 'https://lecture-46-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lecture-46.firebasestorage.app',
    measurementId: 'G-CC3KJJR0PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62Cwj1H-fj4k06yS3s44jEmdcKlpCAQM',
    appId: '1:136527670071:android:2fa077954e418252cb08b2',
    messagingSenderId: '136527670071',
    projectId: 'lecture-46',
    databaseURL: 'https://lecture-46-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lecture-46.firebasestorage.app',
  );
}
